{
  try {
    throw new Win32Exception(W32Errors.ERROR_SHARING_PAUSED);
  }
 catch (  Win32Exception e) {
    assertLastErrorValue(e,W32Errors.ERROR_SHARING_PAUSED,"The remote server has been paused or is in the process of being started.");
  }
}
